-- MySQL Script generated by MySQL Workbench
-- Tue Nov 15 14:30:05 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BrokerTracker
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BrokerTracker
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BrokerTracker` DEFAULT CHARACTER SET utf8 ;
USE `BrokerTracker` ;

-- -----------------------------------------------------
-- Table `BrokerTracker`.`PROD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BrokerTracker`.`PROD` (
  `PRODid` VARCHAR(10) NOT NULL,
  `dataID` VARCHAR(45) NOT NULL,
  `timestamp` TIMESTAMP NOT NULL,
  `topic` VARCHAR(255) NULL,
  PRIMARY KEY (`dataID`, `timestamp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BrokerTracker`.`CONS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BrokerTracker`.`CONS` (
  `consID` VARCHAR(45) NOT NULL,
  `dataID` VARCHAR(45) NOT NULL,
  `timestamp` DATETIME NOT NULL,
  `topic` VARCHAR(255) NULL,
  PRIMARY KEY (`dataID`, `timestamp`, `consID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BrokerTracker`.`WDF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BrokerTracker`.`WDF` (
  `PROD_dataID` VARCHAR(45) NOT NULL,
  `PROD_timestamp` DATETIME NOT NULL,
  `CONS_dataID` VARCHAR(45) NOT NULL,
  `CONS_timestamp` DATETIME NOT NULL,
  PRIMARY KEY (`PROD_dataID`, `PROD_timestamp`, `CONS_dataID`, `CONS_timestamp`),
  INDEX `fk_WDF_PROD_idx` (`PROD_dataID` ASC, `PROD_timestamp` ASC),
  INDEX `fk_WDF_CONS1_idx` (`CONS_dataID` ASC, `CONS_timestamp` ASC),
  CONSTRAINT `fk_WDF_PROD`
    FOREIGN KEY (`PROD_dataID` , `PROD_timestamp`)
    REFERENCES `BrokerTracker`.`PROD` (`dataID` , `timestamp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WDF_CONS1`
    FOREIGN KEY (`CONS_dataID` , `CONS_timestamp`)
    REFERENCES `BrokerTracker`.`CONS` (`dataID` , `timestamp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
